language: python
python:
  - "3.4"
before_install:
  - sudo apt-get install -qq sloccount
install:
  - "pip install -r requirements.txt"
  - "pip install pyflakes"
  - "pip install pep8"
script: "cd mysite; python manage.py jenkins --enable-coverage"