language: python
python:
  - "3.4"
install: "pip install -r requirements.txt"
install: "pip install pyflakes"
install: "pip install pep8"
script: "cd mysite; python manage.py jenkins --enable-coverage"